version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - .:/var/www/html
      - xdebug-data:/tmp/xdebug:cached
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=teste
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 9000:9000 # Porta do Xdebug
    tty: true

  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=teste
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./.docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=teste@teste.com
      - PGADMIN_DEFAULT_PASSWORD=teste
    depends_on:
      - db

volumes:
  xdebug-data:
    name: teste_xdebug-data
