version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=teste
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=teste
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
